/**
 * Generated types from OpenAPI spec.
 *
 * This file is auto-generated by running `npm run gen:types` in CI or locally
 * after server contract changes. Do not edit manually.
 *
 * To regenerate:
 *   npm run gen:types  # requires sibling scxml-http-server checkout
 */

export interface components {
  schemas: {
    Snapshot: {
      instance_id: string;
      configuration: string[];
      datamodel: Record<string, unknown> | null;
      done: boolean;
      execution_status: 'idle' | 'running' | 'completed' | 'error';
      active_states: StateInfo[];
    };
    StateInfo: {
      id: string;
      status: 'running' | 'completed' | 'error';
      type: 'atomic' | 'compound' | 'parallel' | 'final' | 'history';
    };
    HealthStatus: {
      status: string;
    };
    EngineError: {
      error: string;
    };
  };
}

export interface paths {
  '/healthz': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['HealthStatus'];
          };
        };
      };
    };
  };
  '/instances': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': components['schemas']['Snapshot'][];
          };
        };
      };
    };
  };
  '/statecharts': {
    post: {
      requestBody: {
        content: {
          'application/json': {
            document: string;
            instance_id?: string;
          };
        };
      };
      responses: {
        201: {
          content: {
            'application/json': components['schemas']['Snapshot'];
          };
        };
        400: {
          content: {
            'application/json': components['schemas']['EngineError'];
          };
        };
      };
    };
  };
}
