/**
 * Public type aliases for the SCXML HTTP Engine REST API.
 *
 * Types from the server's OpenAPI spec are generated by `openapi-typescript`
 * into `src/generated.ts` (gitignored). This file re-exports them with
 * convenient aliases and adds client-specific utilities.
 *
 * Use `import('./generated')` via inline type import so these aliases
 * always resolve to whatever `openapi-typescript` generates.
 */

// Convenience aliases for the public API
export type InstanceSnapshot = import('./generated').components['schemas']['Snapshot'];
export type StateInfo = import('./generated').components['schemas']['StateInfo'];
export type HealthStatus = import('./generated').components['schemas']['HealthStatus'];
export type EngineError = import('./generated').components['schemas']['EngineError'];
export type ExecutionStatus = InstanceSnapshot['execution_status'];

/** Discriminated union for consistent API responses. */
export type Ok<T> = { ok: true; data: T };
export type Err = { ok: false; error: string };
export type Result<T> = Ok<T> | Err;

/** Configuration for the EngineClient. */
export interface EngineConfig {
  /** Base URL of the scxml-http-engine server (e.g. "http://localhost:4000"). */
  baseUrl: string;
}
